alias: 'Harmonizer: Google TV'
description: 'Forward remote buttons when active'
triggers:
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: up
  trigger: device
  id: DPAD_UP
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: down
  trigger: device
  id: DPAD_DOWN
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: left
  trigger: device
  id: DPAD_LEFT
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: right
  trigger: device
  id: DPAD_RIGHT
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: select
  trigger: device
  id: DPAD_CENTER
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: back
  trigger: device
  id: BACK
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: menu
  trigger: device
  id: MENU
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: exit
  trigger: device
  id: HOME
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: dvr
  trigger: device
  id: DVR
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: guide
  trigger: device
  id: GUIDE
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: info
  trigger: device
  id: INFO
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: play
  trigger: device
  id: MEDIA_PLAY
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: pause
  trigger: device
  id: MEDIA_PAUSE
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: stop
  trigger: device
  id: MEDIA_STOP
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: record
  trigger: device
  id: MEDIA_RECORD
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: channel_up
  trigger: device
  id: CHANNEL_UP
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: channel_down
  trigger: device
  id: CHANNEL_DOWN
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_0
  trigger: device
  id: '0'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_1
  trigger: device
  id: '1'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_2
  trigger: device
  id: '2'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_3
  trigger: device
  id: '3'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_4
  trigger: device
  id: '4'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_5
  trigger: device
  id: '5'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_6
  trigger: device
  id: '6'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_7
  trigger: device
  id: '7'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_8
  trigger: device
  id: '8'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_9
  trigger: device
  id: '9'
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: number_enter
  trigger: device
  id: ENTER
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: red
  trigger: device
  id: PROG_RED
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: green
  trigger: device
  id: PROG_GREEN
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: yellow
  trigger: device
  id: PROG_YELLOW
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: blue
  trigger: device
  id: PROG_BLUE
conditions:
- condition: state
  entity_id: media_player.tx_rz810
  state:
  - GOOGLE TV
  attribute: source
actions:
- action: remote.send_command
  target:
    entity_id: remote.family_room_google_tv
  data:
    num_repeats: 1
    delay_secs: 0
    hold_secs: 0
    command: '{{ trigger.id }}'
mode: queued
max: 10
