alias: 'Harmonizer: off'
description: 'Turn off all family-room media devices'
triggers:
- domain: mqtt
  device_id: 8679b73f0fe819ef8ba86f5ff4579a92
  type: button_short_press
  subtype: 'off'
  trigger: device
conditions: []
actions:
- action: automation.trigger
  data:
    skip_condition: true
  target:
    entity_id: automation.turn_off_family_room_media_devices
mode: single
