# Generates include/portal_pages.h from portal/ so the pages stay editable as
# real HTML/CSS while the firmware ships a single binary (no filesystem,
# no flash partition, no RAM cost beyond serving straight from flash).
import os


def _project_dir():
    try:
        env = Import("env")  # noqa: F821 - provided by SCons/PlatformIO
    except NameError:
        env = None
    if env is not None:
        return env["PROJECT_DIR"]
    # Import("env") returns None when SCons runs this script without the
    # construction environment exported. Fall back to the SCons project
    # root, which for `pio run` is the PlatformIO project directory.
    try:
        return Dir("#").abspath  # noqa: F821 - provided by SCons
    except NameError:
        pass
    try:
        return GetLaunchDir()  # noqa: F821 - provided by SCons
    except NameError:
        pass
    # Standalone execution (editor lint, smoke test): this script lives in
    # <project>/scripts/.
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


PROJECT_DIR = _project_dir()
PORTAL_DIR = os.path.join(PROJECT_DIR, "portal")
OUT_PATH = os.path.join(PROJECT_DIR, "include", "portal_pages.h")

SOURCES = (
    ("PORTAL_REVIEW_HTML", "review.html"),
    ("PORTAL_NETWORK_HTML", "network.html"),
    ("PORTAL_SMART_HUB_HTML", "smart_hub.html"),
    ("PORTAL_REBOOT_HTML", "reboot.html"),
    ("PORTAL_APPLIED_HTML", "applied.html"),
    ("PORTAL_CSS", "portal.css"),
)

lines = [
    "// Auto-generated by scripts/embed_portal.py from portal/. Do not edit.",
    "#ifndef PORTAL_PAGES_H",
    "#define PORTAL_PAGES_H",
    "",
    "#include <Arduino.h>",
    "",
]
for symbol, filename in SOURCES:
    path = os.path.join(PORTAL_DIR, filename)
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    if ')PORTAL"' in text:
        raise RuntimeError("portal file %s contains the raw-literal terminator" % filename)
    lines.append('static const char %s[] PROGMEM = R"PORTAL(%s)PORTAL";' % (symbol, text))
    lines.append("")
lines += ["#endif", ""]

rendered = "\n".join(lines)

previous = None
if os.path.isfile(OUT_PATH):
    with open(OUT_PATH, "r", encoding="utf-8") as handle:
        previous = handle.read()
if previous != rendered:
    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print("embed_portal: wrote %s" % OUT_PATH)
